<link rel="stylesheet" href="/assets/css/sidebar.css">
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3 class="text-center">SoftStore</h3>
        </div>

        <ul class="list-unstyled components">
            <p><i class="fas fa-tachometer-alt"></i> Dashboard</p>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="#">Home 1</a>
                    </li>
                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">About</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Page 1</a>
                    </li>
                    <li>
                        <a href="#">Page 2</a>
                    </li>
                    <li>
                        <a href="#">Page 3</a>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
<!--            <li>-->
<!--                <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>-->
<!--            </li>-->
        </ul>
    </nav>
    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <h2>Bem Vindo(a) !</h2>
                    </li>
                </ul>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">senawalderlan@gmail.com</a>
                        </li>
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="#">Page</a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="#">Page</a>-->
<!--                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" href=/logout"><i class="fas fa-sign-out-alt"></i> Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="card mb-3 col-md-6">
                <div class="row no-gutters">
                    <div class="col-md-4 text-center">
                        <br>
                        <br>
                        <br>
                        <i class="fas fa-chart-line" style="font-size: 100px; color: #8f2fcc;"></i>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title card-header">Pedidos cadastrados</h5>
                            <h1 class="card-text text-center" style="font-size: 90px;">
                                12
                            </h1>
                            <p class="card-text text-center"><small class="text-muted">Total de pedidos cadastrado no sistema.</small></p>

                            <a class="text-center" href="/administracao/cadastrar-novo-pedido">
                                <button class="btn btn-sm btn-dark"><i class="fas fa-edit"></i> Adicionar novo pedido</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mb-3 col-md-6">
                <div class="row no-gutters">
                    <div class="col-md-4 text-center">
                        <br>
                        <br>
                        <br>
                        <i class="fas fa-clipboard-list" style="font-size: 100px; color: #8f2fcc;"></i>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title card-header">Lista de Pedidos</h5>
                            <h1 class="card-text text-center" style="font-size: 90px;">
                                12
                            </h1>
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                            <p class="text-center">
                                <button class="btn btn-sm btn-dark"><i class="fas fa-list"></i> Listar pedidos cadastrados</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
