<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Página não encontrada.</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body class="bg-danger text-white">
<div class="container">
    <div class="row text-center">
        <div class="col-md-12">
            <br>
            <br>
            <br>
            <br>
            <br>
            <h1>403</h1>
            <h2>:)</h2>
            <h3>Acesso Negado.</h3>
            <p>Você não tem permissão para acessar esse recurso.</p>
            <p>
                <button class="btn btn-danger btn-sm">Tire me daqui !</button>
            </p>
        </div>
    </div>
</div>
</body>
</html>