<ul class="list-unstyled components">
    <p><i class="fas fa-tachometer-alt"></i> Dashboard</p>
<!--    <li class="active">-->
<!--        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>-->
<!--        <ul class="collapse list-unstyled" id="homeSubmenu">-->
<!--            <li>-->
<!--                <a href="#">Home 1</a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="#">Home 2</a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="#">Home 3</a>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </li>-->
    <li class="active">
        <a href="https://github.com/WalderlanSena/softExpert" target="_blank">Sobre</a>
    </li>
    <li>
        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-cart-plus"></i> Pedidos</a>
        <ul class="collapse list-unstyled" id="pageSubmenu">
            <li>
                <a href="/administracao/cadastrar-novo-pedido">Cadastrar</a>
            </li>
            <li>
                <a href="/administracao/pedidos">Listar</a>
            </li>
        </ul>
    </li>
</ul>