<link rel="stylesheet" href="/assets/css/sidebar.css">
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3 class="text-center">
                <a href="/administracao">SoftStore</a>
            </h3>
        </div>

        <ul class="list-unstyled components">
            <p><i class="fas fa-tachometer-alt"></i> Dashboard</p>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="#">Home 1</a>
                    </li>
                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">About</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Page 1</a>
                    </li>
                    <li>
                        <a href="#">Page 2</a>
                    </li>
                    <li>
                        <a href="#">Page 3</a>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <!--            <li>-->
            <!--                <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>-->
            <!--            </li>-->
            <!--            <li>-->
            <!--                <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>-->
            <!--            </li>-->
        </ul>
    </nav>
    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <h2><i class="fas fa-cart-plus"></i> Pedidos</h2>
                    </li>
                </ul>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">senawalderlan@gmail.com</a>
                        </li>
                        <!--                        <li class="nav-item">-->
                        <!--                            <a class="nav-link" href="#">Page</a>-->
                        <!--                        </li>-->
                        <!--                        <li class="nav-item">-->
                        <!--                            <a class="nav-link" href="#">Page</a>-->
                        <!--                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" href="/logout"><i class="fas fa-sign-out-alt"></i> Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="card">
            <div class="card-header bg-dark text-white">
                <h4><i class="fas fa-plus"></i> Cadastrar Pedido</h4>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="pedido" class="col-form-label">Pedido</label>
                                <input type="text" class="form-control" placeholder="Nome do pedido" name="pedido" value="">
                            </div>
                            <div class="col-md-4">
                                <label for="codigo" class="col-form-label">Código</label>
                                <input type="text" class="form-control" placeholder="Código do produto" name="codigo" value="">
                            </div>

                            <div class="col-md-4">
                                <label for="tipo" class="col-form-label">Tipo</label>
                                <input type="text" class="form-control" placeholder="Tipo do produto" name="tipo" value="">
                            </div>
                            <hr>
                            <div class="col-md-6">
                                <br>
                                <label for="descricao">Descrição</label>
                                <textarea name="descricao" class="form-control" id="descricao" cols="20" rows="5" style="resize: none;" placeholder="Descrição do Produto"></textarea>
                                <div class="col-xs-6">
                                    <label for="valor" class="col-form-label">Valor do produto</label>
                                    <input type="number" class="form-control" name="valor" placeholder="0.0">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <br>

                                <div class="col-xs-12">
                                    <label for="quantidade">Quantidade de Produtos</label>
                                    <input type="number" class="form-control" id="quantidade" name="quantidade" placeholder="Quantidade de Produtos">
                                </div>
                                <br>
                                <div class="col-xs-12">
                                    <div class="col-xs-6">
                                        <label for="imposto">Imposto sob o produto %</label>
                                        <input type="number" class="form-control" id="imposto" name="imposto" placeholder="Valor do Imposto sob o produto">
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>

            <div class="card-footer">
                <p class="text-right">
                    <button class="btn btn-dark btn-lg"><i class="far fa-save"></i> Salvar</button>
                </p>
            </div>
        </div>
    </div>
</div>